# Increase the heap size for the Gradle daemon.
# Default is 2048m, which might not be enough for some builds.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError

# AndroidX support
android.useAndroidX=true
# Enable Jetifier to convert third-party libraries to AndroidX
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official
